### PR TITLE
Registered User's Data

### PR DESCRIPTION
**Pull request by jdeshaies23**
I generated random data for these tables. Some looks foreign but we could always change that later. It does the job for now.

### CODE REVIEW

**Comment by EthanDRaymond** [comment]
Server isn't liking the code. Got the error:
`INSERT INTO Users VALUES (1, "tincidunt@hendrerit.net", 1, "Jageoid", "Noelani", "Livingston", "ilovecats", 50, 8128816367, "f", 30000, NULL, NULL, NULL)`
`Column count doesn't match value count at row 1`

**Comment by EthanDRaymond** [comment]
Also Got:

```
Static analysis:

4 errors were found during analysis.

A comma or a closing bracket was expected (near "-939" at position 78)
An opening bracket followed by a set of values was expected. (near "1" at position 84)
Unexpected token. (near "1" at position 84)
Unexpected token. (near ")" at position 85)
```

**Comment by jdeshaies23** [comment]
Took out the NULLs.

**Comment by EthanDRaymond** [comment]
@jdeshaies23 I can't see thee changes. Looks like they're still there.

**Pull request closed without merging**
